name: core_playlist
description: "Playlist domain entities and use cases."
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  collection: ^1.18.0
  meta: ^1.15.0
  rxdart: ^0.28.0
  core_foundation:
    path: ../core_foundation
  core_cache:
    path: ../core_cache

dev_dependencies:
  test: ^1.25.0
  mocktail: ^1.0.3
  lints: ^5.0.0
