name: channel_cctv
description: "Haunted surveillance channel implementation."
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.3
  collection: ^1.18.0
  channel_api:
    path: ../channel_api
  core_ui:
    path: ../core_ui
  core_foundation:
    path: ../core_foundation
  core_playlist:
    path: ../core_playlist
  core_cache:
    path: ../core_cache

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
