name: infra_signed_urls
description: "Signed URL fetching adapter."
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  http: ^1.2.0
  retry: ^3.1.2
  core_cache:
    path: ../core_cache
  core_foundation:
    path: ../core_foundation

dev_dependencies:
  test: ^1.25.0
  mocktail: ^1.0.3
  lints: ^5.0.0
