name: infra_firestore
description: "Firestore playlist adapter."
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.4.4
  core_playlist:
    path: ../core_playlist
  core_foundation:
    path: ../core_foundation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  fake_cloud_firestore: ^3.0.0
